<ul class="icon-left-cart">
        <li>
                <?php

                        echo $block->getLayout()

                        ->createBlock('Magento\Cms\Block\Block')

                        ->setBlockId('icon-left-cart')

                        ->toHtml();

                ?>
        </li>

        <li>
                <?php
                        echo $block->getLayout()

                        ->createBlock('Magento\Cms\Block\Block')

                        ->setBlockId('icon-left-cart-2')

                        ->toHtml();

                ?>
        </li>
</ul>
