<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
$swatch = json_decode($block->getJsonConfig(), true)['attributes'][93]['options'];
?>
<?php
/** @var $block \Magento\Swatches\Block\Product\Renderer\Configurable */
/** @var \Magento\Swatches\ViewModel\Product\Renderer\Configurable $configurableViewModel */
$configurableViewModel = $block->getConfigurableViewModel()
?>
<div class="swatch-opt" data-role="swatch-options"></div>
<select class = "swatch-select color">
<option value = "0" option-id="0">Choose an options ... </option>
<?php foreach($swatch as $swa) {
    if($swa['products']) { ?>
        <option value="<?= $swa['id']?>" option-id="<?= $swa['id'] ?>" ><?= $swa['label']?></option>
<?php 
    } else { 
?>
        <option value="<?= $swa['id']?>" option-id="<?= $swa['id'] ?>" option-empty="true" disabled="disabled" class="disabled" ><?= $swa['label']?></option>
<?php }
}
?>
</select>

<script type="text/x-magento-init">
    {
        "[data-role=swatch-options]": {
            "Magento_Swatches/js/swatch-renderer": {
                "jsonConfig": <?= /* @noEscape */ $swatchOptions = $block->getJsonConfig() ?>,
                "jsonSwatchConfig": <?= /* @noEscape */ $swatchOptions = $block->getJsonSwatchConfig() ?>,
                "mediaCallback": "<?= $block->escapeJs($block->escapeUrl($block->getMediaCallback())) ?>",
                "gallerySwitchStrategy": "<?= $block->escapeJs($block->getVar('gallery_switch_strategy', 'Magento_ConfigurableProduct')) ?: 'replace'; ?>",
                "jsonSwatchImageSizeConfig": <?= /* @noEscape */ $block->getJsonSwatchSizeConfig() ?>,
                "showTooltip": <?= $block->escapeJs($configurableViewModel->getShowSwatchTooltip()) ?>
            }
        },
        "*" : {
            "Magento_Swatches/js/catalog-add-to-cart": {}
        }
    }
</script>
