<div class="copyright-bottom-border">
    <div class="copyright-bottom">
        <div>
            <?php
                        echo $block->getLayout()

                        ->createBlock('Magento\Cms\Block\Block')

                        ->setBlockId('copyright-bottom')

                        ->toHtml();
            ?>
        </div>
        <div>
            <?php
                        echo $block->getLayout()

                        ->createBlock('Magento\Cms\Block\Block')

                        ->setBlockId('visa-bottom')

                        ->toHtml();
            ?>
        </div>
    </div>
</div>