<div class="list-link-footer">
    <div class="item-child">
            <h2>
                <?php

                    echo $block->getLayout()

                    ->createBlock('Magento\Cms\Block\Block')

                    ->setBlockId('list-tittle-footer')

                    ->toHtml();

                ?>
            </h2>
            <div>
                <?php

                    echo $block->getLayout()

                    ->createBlock('Magento\Cms\Block\Block')

                    ->setBlockId('list-link-footer')

                    ->toHtml();

                ?>
            </div>
        </div>
        <div class="item-child">
            <h2>
                <?php

                    echo $block->getLayout()

                    ->createBlock('Magento\Cms\Block\Block')

                    ->setBlockId('list-tittle-footer-2')

                    ->toHtml();

                ?>
            </h2>
            <div>
                <?php

                    echo $block->getLayout()

                    ->createBlock('Magento\Cms\Block\Block')

                    ->setBlockId('list-link-footer-2')

                    ->toHtml();

                ?>
            </div>
        </div>
        <div class="item-child">
            <h2>
                <?php

                    echo $block->getLayout()

                    ->createBlock('Magento\Cms\Block\Block')

                    ->setBlockId('list-tittle-footer-3')

                    ->toHtml();

                ?>
            </h2>
            <div>
                <?php

                    echo $block->getLayout()

                    ->createBlock('Magento\Cms\Block\Block')

                    ->setBlockId('list-link-footer-3')

                    ->toHtml();

                ?>
            </div>
        </div>
        <div class="icon-social-2">
        <?php

            echo $block->getLayout()

            ->createBlock('Magento\Cms\Block\Block')

            ->setBlockId('list-link-footer-4')

            ->toHtml();

        ?>
        </div>
    </div>
