<div class="subscribe-to-our-newsletter">
        <?php

            echo $block->getLayout()

            ->createBlock('Magento\Cms\Block\Block')

            ->setBlockId('subscribe-to-our-newsletter')

            ->toHtml();

        ?>
</div>
<div class="sign-up-below">
        <?php

            echo $block->getLayout()

            ->createBlock('Magento\Cms\Block\Block')

            ->setBlockId('sign-up-below')

            ->toHtml();

        ?>
</div>