<?php

echo $block->getLayout()

->createBlock('Magento\Cms\Block\Block')

->setBlockId('goes-well-with')

->toHtml();

?>

<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $(".product-items").slick({
                infinite: true,
                speed: 300,
                slidesToShow: 3,
                slidesToScroll: 3
            });
        });
    });
</script>