<div class="box-naturally">
    <div class="naturally-smells">
        <?php
                    echo $block->getLayout()

                    ->createBlock('Magento\Cms\Block\Block')

                    ->setBlockId('naturally-smells')

                    ->toHtml();
        ?>
    </div>
    <div class="line">
        <?php
                    echo $block->getLayout()

                    ->createBlock('Magento\Cms\Block\Block')

                    ->setBlockId('line')

                    ->toHtml();
        ?>
    </div>
    <div class="vani-coco">
        <?php
                    echo $block->getLayout()

                    ->createBlock('Magento\Cms\Block\Block')

                    ->setBlockId('vani-coco-lime')

                    ->toHtml();
        ?>
    </div>
</div>