<div>
    <div class="product-payment">
        <?php
                echo $block->getLayout()

                ->createBlock('Magento\Cms\Block\Block')

                ->setBlockId('product-payment')

                ->toHtml();

        ?>
    </div>
</div>

<div>
    <div class="afterpay-product">
        <?php
                echo $block->getLayout()

                ->createBlock('Magento\Cms\Block\Block')

                ->setBlockId('afterpay-product')

                ->toHtml();
        ?>
    </div>
</div>